### ISSUE TITLE
Find player by their friend code

### ISSUE THREAD

**Issue by oha-4** [VikeMK/Lounge-API#25]
Japanese often participate in MKB competitions where they register only their name and friend code without linking it to their mkc or lounge account. If I want to know the strength of the players in the same room, I have to search for the friend code on multiple sites by myself. However, if we could search for a player directly by their friend code using the Lounge API, it would be a very good way to find out the strength of the player. Is it possible to do that?

**Comment by VikeMK** [comment]
I have added this now, here is an example with my FC: https://www.mk8dx-lounge.com/api/player?fc=2137-9486-2022
You can also do it by searching "switch=<fc>" in the leaderboard search:
![image](https://user-images.githubusercontent.com/62164219/182009304-f4c8435d-69ce-496b-953a-b374c2257474.png)
